# Generated by Django 6.0.3 on 2026-03-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL(
        """
             INSERT INTO store_collection (title)
             VALUES ('collection1')
        """,
        """
            DELETE FROM store_collection
            WHERE title = 'collection1'
        """
        )
    ]
